name: Trigger auto deployment for soe-studio-ops-qdrant

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/soe-studio-ops-qdrant-AutoDeployTrigger-710c1cf6-1627-4d76-84f8-9dad65054e0b.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOESTUDIOOPSQDRANT_AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: azureopenaiacr.azurecr.io
          registryUsername: ${{ secrets.SOESTUDIOOPSQDRANT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SOESTUDIOOPSQDRANT_REGISTRY_PASSWORD }}
          containerAppName: soe-studio-ops-qdrant
          resourceGroup: SOE-StudioOps-Dev-Test
          imageToBuild: azureopenaiacr.azurecr.io/soe-studio-ops-qdrant:${{ github.sha }}
          dockerfilePath: Dockerfile

     

